"""Initial migration

Revision ID: 6babc48832b0
Revises: 
Create Date: 2024-08-24 16:26:44.254260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6babc48832b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_chats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_chats_id'), 'private_chats', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('public_chats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_chats_id'), 'public_chats', ['id'], unique=False)
    op.create_index(op.f('ix_public_chats_name'), 'public_chats', ['name'], unique=True)
    op.create_table('user_private_chats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('private_chat_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['private_chat_id'], ['private_chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'private_chat_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('public_chat_id', sa.Uuid(), nullable=True),
    sa.Column('private_chat_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['private_chat_id'], ['private_chats.id'], ),
    sa.ForeignKeyConstraint(['public_chat_id'], ['public_chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('user_public_chats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('public_chat_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['public_chat_id'], ['public_chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'public_chat_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('user_public_chats')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('user_private_chats')
    op.drop_index(op.f('ix_public_chats_name'), table_name='public_chats')
    op.drop_index(op.f('ix_public_chats_id'), table_name='public_chats')
    op.drop_table('public_chats')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_private_chats_id'), table_name='private_chats')
    op.drop_table('private_chats')
    # ### end Alembic commands ###
